$docs = "~\Documents"
$dt = "~\Desktop"
$helix_config = "~\scoop\persist\helix"
$nvimconfig = "~\AppData\Local\nvim"
$pwshconfig = "~\Documents\WindowsPowerShell"
$dl = "~\Downloads"
$msfs_content = "D:\Games\Microsoft Flight Simulator\Content"
